-- Create table for Mod Configuration
CREATE TABLE IF NOT EXISTS mod_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_name TEXT NOT NULL,
    config_data TEXT NOT NULL, -- The formatted string: "Name|Offset|Bytes;..."
    version_code INT DEFAULT 1,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert a default config (The one we just implemented)
INSERT INTO mod_configs (config_name, config_data, is_active, version_code)
VALUES (
    'LQM Default',
    'Hack Map (0x5154A00)|5154A00|D2800036;Cam Gần|5EF319C|1E2F1001;Cam Xa|5EF3198|1E2F9000;Cam Siêu Xa|5EF31A8|1E201001;Hiện Tên Cấm Chọn|5BF6B8C|D2800037;Hiện LSĐ|5A26C64|D2800020D65F03C0;Hiện Avatar|5A01A30|D2800000D65F03C0;Hiện Bổ Trợ|5D8415C|D503201F;Hiện Ulti 1|5BECAE4|D503201F;Hiện Ulti 2|5BECB88|52800033;Hiện Rank|5CB0AC4|D503201F;Fix FPS 1|5C34744|D65F03C0;Fix FPS 2|5C34644|D65F03C0;3 Nút|5C28638|52800020D65F03C0;Aim|61A36D0|528000E3D65F03C0',
    TRUE,
    1
);

-- Create RLS policies (adjust as needed, keeping it open for read for now for api)
ALTER TABLE mod_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "mod_configs"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "mod_configs"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "mod_configs"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (true);
